services:
  mysql:
    image: mysql:8.0.44
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command:
      - --gtid_mode=ON
      - --enforce_gtid_consistency=ON
      - --log-bin=mysql-bin
      - --server-id=1
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
