//go:build integration

package api

import (
	"database/sql"
	"log/slog"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/schemabot/pkg/schema"
)

// insertSettingWithID inserts a settings row with an explicit identity value,
// the way an id-preserving bulk load writes rows.
func insertSettingWithID(t *testing.T, db *sql.DB, id int64, key string) {
	t.Helper()
	_, err := db.ExecContext(t.Context(),
		`INSERT INTO settings (id, setting_key, setting_value) VALUES ($1, $2, '')`, id, key)
	require.NoError(t, err)
}

// insertSettingDefaultID inserts a settings row drawing its id from the
// identity sequence, returning the id and any insert error.
func insertSettingDefaultID(t *testing.T, db *sql.DB, key string) (int64, error) {
	t.Helper()
	var id int64
	err := db.QueryRowContext(t.Context(),
		`INSERT INTO settings (setting_key, setting_value) VALUES ($1, '') RETURNING id`, key).Scan(&id)
	return id, err
}

// After an explicit-id bulk load, the identity sequences still point below
// the loaded rows — GENERATED BY DEFAULT AS IDENTITY accepts explicit values
// without advancing the sequence — so the next default insert collides with
// a loaded row. Resyncing advances every identity sequence past its column's
// stored maximum, letting default inserts resume above the loaded ids.
func TestResyncPostgresIdentitySequences_UnblocksDefaultInsertsAfterExplicitIDLoad(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}))
	require.NoError(t, EnsureSchema(dsn, logger, WithDialect(schema.DialectPostgres)))

	insertSettingWithID(t, db, 1, "loaded-1")
	insertSettingWithID(t, db, 2, "loaded-2")
	insertSettingWithID(t, db, 3, "loaded-3")

	// The untouched sequence hands out id 1, colliding with a loaded row.
	_, err := insertSettingDefaultID(t, db, "collides")
	require.Error(t, err, "default insert after an explicit-id load must collide with a loaded id")
	require.Contains(t, err.Error(), "duplicate key", "collision must be the primary-key unique violation")

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	id, err := insertSettingDefaultID(t, db, "after-resync")
	require.NoError(t, err)
	assert.Equal(t, int64(4), id, "the first default insert after the resync draws max+1")
}

// A resync never rewinds a sequence: on a table whose sequence is already
// past the stored maximum (id gaps left by deleted rows), and on tables that
// never saw an explicit id, the resync is a no-op — re-running it hands out
// fresh ids rather than reusing a deleted row's id.
func TestResyncPostgresIdentitySequences_NeverRewindsAheadSequences(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}))
	require.NoError(t, EnsureSchema(dsn, logger, WithDialect(schema.DialectPostgres)))

	first, err := insertSettingDefaultID(t, db, "kept")
	require.NoError(t, err)
	gap, err := insertSettingDefaultID(t, db, "deleted")
	require.NoError(t, err)
	require.Greater(t, gap, first)

	_, err = db.ExecContext(t.Context(), `DELETE FROM settings WHERE id = $1`, gap)
	require.NoError(t, err)

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	next, err := insertSettingDefaultID(t, db, "fresh")
	require.NoError(t, err)
	assert.Greater(t, next, gap, "a resync must not rewind the sequence into the deleted row's id")
}
