package api

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/block/spirit/pkg/utils"
)

// ResyncPostgresIdentitySequences advances the backing sequence of every
// identity column on SchemaBot's own storage tables (the embedded schema
// files) past the column's largest stored value. PostgreSQL's GENERATED BY
// DEFAULT AS IDENTITY accepts explicit values without advancing the
// sequence, so after an explicit-id bulk load — a cross-dialect data move
// that preserves ids, or a restore from a dump without sequence state — the
// next default insert collides with a loaded row's id. Run the resync after
// any such load and before default inserts resume.
//
// Sequences are only ever advanced, never rewound: a sequence whose next
// draw is already past the stored maximum — id gaps from deleted rows, or a
// sequence parked ahead with an explicit setval or RESTART — is left
// untouched, so the resync is idempotent. Descending sequences are skipped
// with a warning: a stored-maximum resync is only meaningful for ascending
// draws.
//
// The stored-maximum read and the sequence update are not atomic — run the
// resync only after the load has fully committed. A concurrent explicit-id
// insert can commit a new maximum after the read and leave its table's
// sequence behind again; a concurrent default insert cannot cause a rewind
// (the advance-only guard suppresses the update) but can leave the sequence
// where the concurrent draw put it rather than at the stored maximum.
func ResyncPostgresIdentitySequences(ctx context.Context, db *sql.DB, logger *slog.Logger) error {
	tables, _, err := readEmbeddedPostgresSchemaFiles()
	if err != nil {
		return fmt.Errorf("read embedded PostgreSQL storage schema: %w", err)
	}
	missing, err := missingPostgresTables(ctx, db, tables)
	if err != nil {
		return fmt.Errorf("check target for storage tables: %w", err)
	}
	if len(missing) == len(tables) {
		return fmt.Errorf("none of the %d storage tables exist in the target database; it does not look like SchemaBot's storage database", len(tables))
	}
	columns, err := postgresIdentityColumns(ctx, db, tables)
	if err != nil {
		return fmt.Errorf("find identity columns on storage tables: %w", err)
	}

	advanced := 0
	skipped := 0
	for _, col := range columns {
		newValue, outcome, err := advancePostgresIdentitySequence(ctx, db, col)
		if err != nil {
			return fmt.Errorf("resync identity column %s.%s: %w", col.table, col.column, err)
		}
		switch outcome {
		case sequenceAdvanced:
			advanced++
			logger.Info("advanced identity sequence past stored maximum",
				"table", col.table, "column", col.column, "sequence_value", newValue)
		case sequenceSkippedEmptyTable:
			skipped++
			logger.Debug("identity column has no stored rows; sequence left untouched",
				"table", col.table, "column", col.column)
		case sequenceSkippedAlreadyAhead:
			skipped++
			logger.Debug("identity sequence already at or past stored maximum; left untouched",
				"table", col.table, "column", col.column)
		case sequenceSkippedDescending:
			skipped++
			logger.Warn("identity sequence is descending; resync skipped it — a stored-maximum resync only applies to ascending sequences",
				"table", col.table, "column", col.column)
		}
	}
	logger.Info("identity sequence resync summary",
		"tables", len(tables), "examined", len(columns), "advanced", advanced, "skipped", skipped)
	return nil
}

// postgresIdentityColumn names one identity column on a storage table.
type postgresIdentityColumn struct {
	table  string
	column string
}

// sequenceResyncOutcome reports what a single sequence resync did, so the
// caller can log each skip cause distinctly.
type sequenceResyncOutcome int

const (
	sequenceAdvanced sequenceResyncOutcome = iota
	sequenceSkippedEmptyTable
	sequenceSkippedAlreadyAhead
	sequenceSkippedDescending
)

// postgresIdentityColumns lists every identity column on the given tables in
// the connection's current schema, in a stable order.
func postgresIdentityColumns(ctx context.Context, db *sql.DB, tables []string) ([]postgresIdentityColumn, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_name, column_name
		FROM information_schema.columns
		WHERE table_schema = current_schema() AND is_identity = 'YES'
		  AND table_name = ANY($1)
		ORDER BY table_name, column_name`, tables)
	if err != nil {
		return nil, fmt.Errorf("list identity columns on storage tables: %w", err)
	}
	defer utils.CloseAndLog(rows)

	var columns []postgresIdentityColumn
	for rows.Next() {
		var col postgresIdentityColumn
		if err := rows.Scan(&col.table, &col.column); err != nil {
			return nil, fmt.Errorf("scan identity column row: %w", err)
		}
		columns = append(columns, col)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate identity columns: %w", err)
	}
	return columns, nil
}

// advancePostgresIdentitySequence sets the column's backing sequence to the
// column's stored maximum when the sequence's next draw would otherwise be at
// or below it, so the next default insert draws maximum+1. It reports the
// value set and the outcome; a sequence whose next draw is already past the
// maximum, an empty table, and a descending sequence are left untouched.
func advancePostgresIdentitySequence(ctx context.Context, db *sql.DB, col postgresIdentityColumn) (int64, sequenceResyncOutcome, error) {
	// pg_get_serial_sequence parses its table argument as an SQL name — an
	// unquoted mixed-case name is downcased — so the table is quoted. The
	// column argument is matched verbatim against attribute names and must
	// stay unquoted.
	var sequence sql.NullString
	if err := db.QueryRowContext(ctx,
		`SELECT pg_get_serial_sequence($1, $2)`, quotePostgresIdentifier(col.table), col.column,
	).Scan(&sequence); err != nil {
		return 0, 0, fmt.Errorf("resolve backing sequence for identity column %s.%s: %w", col.table, col.column, err)
	}
	if !sequence.Valid {
		return 0, 0, fmt.Errorf("identity column %s.%s has no backing sequence", col.table, col.column)
	}

	var increment int64
	if err := db.QueryRowContext(ctx,
		`SELECT seqincrement FROM pg_sequence WHERE seqrelid = $1::regclass`, sequence.String,
	).Scan(&increment); err != nil {
		return 0, 0, fmt.Errorf("read increment of sequence %s for identity column %s.%s: %w",
			sequence.String, col.table, col.column, err)
	}
	if increment < 0 {
		return 0, sequenceSkippedDescending, nil
	}

	var storedMax sql.NullInt64
	maxQuery := fmt.Sprintf(`SELECT MAX(%s) FROM %s`,
		quotePostgresIdentifier(col.column), quotePostgresIdentifier(col.table))
	if err := db.QueryRowContext(ctx, maxQuery).Scan(&storedMax); err != nil {
		return 0, 0, fmt.Errorf("read stored maximum of identity column %s.%s: %w", col.table, col.column, err)
	}
	if !storedMax.Valid {
		return 0, sequenceSkippedEmptyTable, nil
	}

	// setval with is_called=true makes the next default insert draw
	// storedMax+increment. The WHERE clause keeps the resync advance-only by
	// comparing against the sequence's next draw, read from the sequence
	// relation itself: once called, the next draw is last_value+increment;
	// before the first draw (is_called false — a fresh sequence, or one
	// parked with setval/RESTART) last_value itself is handed out next. A
	// sequence whose next draw is already past the maximum returns no row.
	// The sequence name comes from pg_get_serial_sequence, which returns it
	// schema-qualified and quoted, so it is safe to interpolate.
	var newValue int64
	guardQuery := fmt.Sprintf(`
		SELECT setval($1::regclass, $2::bigint, true)
		FROM %s
		WHERE last_value + (CASE WHEN is_called THEN $3::bigint ELSE 0 END) <= $2::bigint`,
		sequence.String)
	err := db.QueryRowContext(ctx, guardQuery, sequence.String, storedMax.Int64, increment).Scan(&newValue)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, sequenceSkippedAlreadyAhead, nil
	}
	if err != nil {
		return 0, 0, fmt.Errorf("advance sequence %s for identity column %s.%s to %d: %w",
			sequence.String, col.table, col.column, storedMax.Int64, err)
	}
	return newValue, sequenceAdvanced, nil
}

// quotePostgresIdentifier returns a PostgreSQL double-quoted identifier,
// escaping any embedded double quotes.
func quotePostgresIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
