//go:build integration

package api

import (
	"context"
	"database/sql"
	"log/slog"
	"sort"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/schemabot/pkg/schema"
)

// insertSettingWithID inserts a settings row with an explicit identity value,
// the way an id-preserving bulk load writes rows.
func insertSettingWithID(t *testing.T, db *sql.DB, id int64, key string) {
	t.Helper()
	_, err := db.ExecContext(t.Context(),
		`INSERT INTO settings (id, setting_key, setting_value) VALUES ($1, $2, '')`, id, key)
	require.NoError(t, err)
}

// insertSettingDefaultID inserts a settings row drawing its id from the
// identity sequence, returning the id and any insert error.
func insertSettingDefaultID(t *testing.T, db *sql.DB, key string) (int64, error) {
	t.Helper()
	var id int64
	err := db.QueryRowContext(t.Context(),
		`INSERT INTO settings (setting_key, setting_value) VALUES ($1, '') RETURNING id`, key).Scan(&id)
	return id, err
}

// capturedLogRecord is one log line emitted by a resync, flattened for
// assertions.
type capturedLogRecord struct {
	level   slog.Level
	message string
	attrs   map[string]any
}

// recordingLogHandler captures every record so tests can assert the resync's
// operator-facing log contract: which tables advanced, which were skipped,
// and why.
type recordingLogHandler struct {
	mu      sync.Mutex
	records []capturedLogRecord
}

func (h *recordingLogHandler) Enabled(context.Context, slog.Level) bool { return true }

func (h *recordingLogHandler) Handle(_ context.Context, r slog.Record) error {
	attrs := map[string]any{}
	r.Attrs(func(a slog.Attr) bool {
		attrs[a.Key] = a.Value.Any()
		return true
	})
	h.mu.Lock()
	defer h.mu.Unlock()
	h.records = append(h.records, capturedLogRecord{level: r.Level, message: r.Message, attrs: attrs})
	return nil
}

func (h *recordingLogHandler) WithAttrs([]slog.Attr) slog.Handler { return h }
func (h *recordingLogHandler) WithGroup(string) slog.Handler      { return h }

// recordsForTable returns the captured records whose "table" attr matches.
func (h *recordingLogHandler) recordsForTable(table string) []capturedLogRecord {
	h.mu.Lock()
	defer h.mu.Unlock()
	var out []capturedLogRecord
	for _, r := range h.records {
		if r.attrs["table"] == table {
			out = append(out, r)
		}
	}
	return out
}

// tablesInOrder returns the "table" attr of every captured record, in emit
// order.
func (h *recordingLogHandler) tablesInOrder() []string {
	h.mu.Lock()
	defer h.mu.Unlock()
	var out []string
	for _, r := range h.records {
		if table, ok := r.attrs["table"].(string); ok {
			out = append(out, table)
		}
	}
	return out
}

// resyncLogger returns a logger whose records the test can assert on.
func resyncLogger(t *testing.T) (*slog.Logger, *recordingLogHandler) {
	t.Helper()
	handler := &recordingLogHandler{}
	return slog.New(handler), handler
}

// A target without any SchemaBot storage tables is rejected before sequence
// discovery, preventing an unrelated PostgreSQL database from appearing to
// resync successfully.
func TestResyncPostgresIdentitySequences_RejectsTargetWithoutStorageTables(t *testing.T) {
	_, db := startPostgresStorage(t)
	err := ResyncPostgresIdentitySequences(t.Context(), db, slog.New(slog.DiscardHandler))
	require.ErrorContains(t, err, "none of the")
	require.ErrorContains(t, err, "does not look like SchemaBot's storage database")
}

// After an explicit-id bulk load, the identity sequences still point below
// the loaded rows — GENERATED BY DEFAULT AS IDENTITY accepts explicit values
// without advancing the sequence — so the next default insert collides with
// a loaded row. Resyncing advances every identity sequence past its column's
// stored maximum, letting default inserts resume above the loaded ids.
func TestResyncPostgresIdentitySequences_UnblocksDefaultInsertsAfterExplicitIDLoad(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	require.NoError(t, EnsureSchema(dsn, slog.New(slog.DiscardHandler), WithDialect(schema.DialectPostgres)))
	logger, logs := resyncLogger(t)

	insertSettingWithID(t, db, 1, "loaded-1")
	insertSettingWithID(t, db, 2, "loaded-2")
	insertSettingWithID(t, db, 3, "loaded-3")

	// The untouched sequence hands out id 1, colliding with a loaded row.
	_, err := insertSettingDefaultID(t, db, "collides")
	require.Error(t, err, "default insert after an explicit-id load must collide with a loaded id")
	require.Contains(t, err.Error(), "duplicate key", "collision must be the primary-key unique violation")

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	id, err := insertSettingDefaultID(t, db, "after-resync")
	require.NoError(t, err)
	assert.Equal(t, int64(4), id, "the first default insert after the resync draws max+1")

	records := logs.recordsForTable("settings")
	require.Len(t, records, 1, "the resync logs exactly one outcome per identity column")
	assert.Equal(t, slog.LevelInfo, records[0].level)
	assert.Equal(t, "advanced identity sequence past stored maximum", records[0].message)
	assert.Equal(t, int64(3), records[0].attrs["sequence_value"], "the sequence is set to the stored maximum")

	tables := logs.tablesInOrder()
	assert.True(t, sort.StringsAreSorted(tables), "outcomes are logged in a stable table order: %v", tables)
}

// A sequence that has never handed out a value still resyncs: a fresh
// identity sequence sits at its start value with nothing drawn, so after an
// explicit-id load the very first default insert must draw max+1 — there is
// no earlier default insert to have positioned the sequence.
func TestResyncPostgresIdentitySequences_AdvancesNeverUsedSequence(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	require.NoError(t, EnsureSchema(dsn, slog.New(slog.DiscardHandler), WithDialect(schema.DialectPostgres)))
	logger, logs := resyncLogger(t)

	insertSettingWithID(t, db, 1, "loaded-1")
	insertSettingWithID(t, db, 2, "loaded-2")
	insertSettingWithID(t, db, 3, "loaded-3")

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	id, err := insertSettingDefaultID(t, db, "first-default")
	require.NoError(t, err)
	assert.Equal(t, int64(4), id, "the first-ever default insert draws max+1")

	records := logs.recordsForTable("settings")
	require.Len(t, records, 1)
	assert.Equal(t, "advanced identity sequence past stored maximum", records[0].message)
}

// A resync never rewinds a sequence: on a table whose sequence is already
// past the stored maximum (id gaps left by deleted rows), and on tables that
// never saw an explicit id, the resync is a no-op — re-running it hands out
// fresh ids rather than reusing a deleted row's id.
func TestResyncPostgresIdentitySequences_NeverRewindsAheadSequences(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	require.NoError(t, EnsureSchema(dsn, slog.New(slog.DiscardHandler), WithDialect(schema.DialectPostgres)))
	logger, logs := resyncLogger(t)

	first, err := insertSettingDefaultID(t, db, "kept")
	require.NoError(t, err)
	require.Equal(t, int64(1), first)
	gap, err := insertSettingDefaultID(t, db, "deleted")
	require.NoError(t, err)
	require.Equal(t, int64(2), gap)

	_, err = db.ExecContext(t.Context(), `DELETE FROM settings WHERE id = $1`, gap)
	require.NoError(t, err)

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	next, err := insertSettingDefaultID(t, db, "fresh")
	require.NoError(t, err)
	assert.Equal(t, int64(3), next, "a resync must not rewind the sequence into the deleted row's id")

	records := logs.recordsForTable("settings")
	require.Len(t, records, 1)
	assert.Equal(t, slog.LevelDebug, records[0].level)
	assert.Equal(t, "identity sequence already at or past stored maximum; left untouched", records[0].message)
}

// A sequence parked ahead without ever being drawn — pg_dump emits
// setval(seq, n, false), and RESTART WITH produces the same state — is
// already past the stored maximum and must not be rewound: ids below the
// parked position may be reserved deliberately as headroom.
func TestResyncPostgresIdentitySequences_NeverRewindsParkedAheadSequence(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	require.NoError(t, EnsureSchema(dsn, slog.New(slog.DiscardHandler), WithDialect(schema.DialectPostgres)))
	logger, logs := resyncLogger(t)

	insertSettingWithID(t, db, 1, "loaded-1")
	insertSettingWithID(t, db, 2, "loaded-2")
	insertSettingWithID(t, db, 3, "loaded-3")

	_, err := db.ExecContext(t.Context(), `ALTER TABLE settings ALTER COLUMN id RESTART WITH 1000`)
	require.NoError(t, err)

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	id, err := insertSettingDefaultID(t, db, "parked")
	require.NoError(t, err)
	assert.Equal(t, int64(1000), id, "the parked position is preserved — the resync must not rewind an undrawn sequence")

	records := logs.recordsForTable("settings")
	require.Len(t, records, 1)
	assert.Equal(t, slog.LevelDebug, records[0].level)
	assert.Equal(t, "identity sequence already at or past stored maximum; left untouched", records[0].message)
}

// The resync only touches SchemaBot's own storage tables: an unrelated table
// sharing the schema is never scanned or setval'd, even when its identity
// sequence is behind its stored maximum.
func TestResyncPostgresIdentitySequences_IgnoresForeignTables(t *testing.T) {
	dsn, db := startPostgresStorage(t)
	require.NoError(t, EnsureSchema(dsn, slog.New(slog.DiscardHandler), WithDialect(schema.DialectPostgres)))
	logger, logs := resyncLogger(t)

	_, err := db.ExecContext(t.Context(),
		`CREATE TABLE app_orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note text NOT NULL)`)
	require.NoError(t, err)
	_, err = db.ExecContext(t.Context(), `INSERT INTO app_orders (id, note) VALUES (1, ''), (2, ''), (3, '')`)
	require.NoError(t, err)

	require.NoError(t, ResyncPostgresIdentitySequences(t.Context(), db, logger))

	assert.Empty(t, logs.recordsForTable("app_orders"), "a foreign table is not scanned")
	var id int64
	err = db.QueryRowContext(t.Context(),
		`INSERT INTO app_orders (note) VALUES ('') RETURNING id`).Scan(&id)
	require.Error(t, err, "the foreign table's sequence is untouched, so its default insert still collides")
	require.Contains(t, err.Error(), "duplicate key")
}

// A mixed-case table name resolves and advances: the table argument of
// pg_get_serial_sequence is parsed as an SQL name, so it must arrive quoted
// or the lookup downcases it and fails.
func TestAdvancePostgresIdentitySequence_MixedCaseTable(t *testing.T) {
	_, db := startPostgresStorage(t)

	_, err := db.ExecContext(t.Context(),
		`CREATE TABLE "zAudit" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note text NOT NULL)`)
	require.NoError(t, err)
	_, err = db.ExecContext(t.Context(), `INSERT INTO "zAudit" (id, note) VALUES (1, ''), (2, ''), (3, '')`)
	require.NoError(t, err)

	newValue, outcome, err := advancePostgresIdentitySequence(t.Context(), db,
		postgresIdentityColumn{table: "zAudit", column: "id"})
	require.NoError(t, err)
	assert.Equal(t, sequenceAdvanced, outcome)
	assert.Equal(t, int64(3), newValue)

	var id int64
	err = db.QueryRowContext(t.Context(),
		`INSERT INTO "zAudit" (note) VALUES ('') RETURNING id`).Scan(&id)
	require.NoError(t, err)
	assert.Equal(t, int64(4), id)
}

// A descending identity sequence is skipped: MAX() names the wrong extremum
// for a descending draw, so moving the sequence "forward" to it would hand
// out already-used ids. The sequence is left exactly where it was.
func TestAdvancePostgresIdentitySequence_SkipsDescendingSequence(t *testing.T) {
	_, db := startPostgresStorage(t)

	_, err := db.ExecContext(t.Context(),
		`CREATE TABLE countdown (id bigint GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1 START WITH -1 MINVALUE -1000 MAXVALUE -1) PRIMARY KEY, note text NOT NULL)`)
	require.NoError(t, err)
	_, err = db.ExecContext(t.Context(), `INSERT INTO countdown (id, note) VALUES (-1, ''), (-2, ''), (-3, '')`)
	require.NoError(t, err)

	newValue, outcome, err := advancePostgresIdentitySequence(t.Context(), db,
		postgresIdentityColumn{table: "countdown", column: "id"})
	require.NoError(t, err)
	assert.Equal(t, sequenceSkippedDescending, outcome)
	assert.Zero(t, newValue)

	var id int64
	err = db.QueryRowContext(t.Context(),
		`INSERT INTO countdown (note) VALUES ('') RETURNING id`).Scan(&id)
	require.Error(t, err, "the descending sequence is untouched, so its next draw still collides")
	require.Contains(t, err.Error(), "duplicate key")
}
