package api

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/block/spirit/pkg/utils"
)

// ResyncPostgresIdentitySequences advances every identity column's backing
// sequence in the connection's current schema past the column's largest
// stored value. PostgreSQL's GENERATED BY DEFAULT AS IDENTITY accepts
// explicit values without advancing the sequence, so after an explicit-id
// bulk load — a cross-dialect data move that preserves ids, or a restore
// from a dump without sequence state — the next default insert collides
// with a loaded row's id. Run the resync after any such load and before
// default inserts resume.
//
// Sequences are only ever advanced, never rewound: a sequence already past
// the stored maximum (id gaps from deleted rows) is left untouched, so the
// resync is idempotent and safe on tables that never saw an explicit id.
// The stored-maximum read and the sequence update are not atomic — callers
// must ensure no concurrent default inserts are in flight against the
// affected tables while the resync runs.
func ResyncPostgresIdentitySequences(ctx context.Context, db *sql.DB, logger *slog.Logger) error {
	columns, err := postgresIdentityColumns(ctx, db)
	if err != nil {
		return err
	}

	for _, col := range columns {
		newValue, advanced, err := advancePostgresIdentitySequence(ctx, db, col)
		if err != nil {
			return err
		}
		if advanced {
			logger.Info("advanced identity sequence past stored maximum",
				"table", col.table, "column", col.column, "sequence_value", newValue)
			continue
		}
		logger.Debug("identity sequence already past stored maximum",
			"table", col.table, "column", col.column)
	}
	return nil
}

// postgresIdentityColumn names one identity column in the current schema.
type postgresIdentityColumn struct {
	table  string
	column string
}

// postgresIdentityColumns lists every identity column in the connection's
// current schema, in a stable order.
func postgresIdentityColumns(ctx context.Context, db *sql.DB) ([]postgresIdentityColumn, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_name, column_name
		FROM information_schema.columns
		WHERE table_schema = current_schema() AND is_identity = 'YES'
		ORDER BY table_name, column_name`)
	if err != nil {
		return nil, fmt.Errorf("list identity columns in current schema: %w", err)
	}
	defer utils.CloseAndLog(rows)

	var columns []postgresIdentityColumn
	for rows.Next() {
		var col postgresIdentityColumn
		if err := rows.Scan(&col.table, &col.column); err != nil {
			return nil, fmt.Errorf("scan identity column row: %w", err)
		}
		columns = append(columns, col)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate identity columns: %w", err)
	}
	return columns, nil
}

// advancePostgresIdentitySequence sets the column's backing sequence to the
// column's stored maximum when the sequence is behind it, so the next default
// insert draws maximum+1. It reports the value set and whether an advance
// happened; a sequence at or past the maximum, or an empty table, is left
// untouched.
func advancePostgresIdentitySequence(ctx context.Context, db *sql.DB, col postgresIdentityColumn) (int64, bool, error) {
	var sequence sql.NullString
	if err := db.QueryRowContext(ctx,
		`SELECT pg_get_serial_sequence($1, $2)`, col.table, col.column,
	).Scan(&sequence); err != nil {
		return 0, false, fmt.Errorf("resolve backing sequence for identity column %s.%s: %w", col.table, col.column, err)
	}
	if !sequence.Valid {
		return 0, false, fmt.Errorf("identity column %s.%s has no backing sequence", col.table, col.column)
	}

	var storedMax sql.NullInt64
	maxQuery := fmt.Sprintf(`SELECT MAX(%s) FROM %s`,
		quotePostgresIdentifier(col.column), quotePostgresIdentifier(col.table))
	if err := db.QueryRowContext(ctx, maxQuery).Scan(&storedMax); err != nil {
		return 0, false, fmt.Errorf("read stored maximum of identity column %s.%s: %w", col.table, col.column, err)
	}
	if !storedMax.Valid {
		return 0, false, nil
	}

	// setval with is_called=true makes the next default insert draw
	// storedMax+1. The WHERE clause keeps the resync advance-only:
	// pg_sequence_last_value is NULL for a never-used sequence, and a
	// sequence already at or past the maximum returns no row.
	var newValue int64
	err := db.QueryRowContext(ctx, `
		SELECT setval($1::regclass, $2::bigint, true)
		WHERE $2::bigint > COALESCE(pg_sequence_last_value($1::regclass), 0)`,
		sequence.String, storedMax.Int64,
	).Scan(&newValue)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, fmt.Errorf("advance sequence %s for identity column %s.%s to %d: %w",
			sequence.String, col.table, col.column, storedMax.Int64, err)
	}
	return newValue, true, nil
}

// quotePostgresIdentifier returns a PostgreSQL double-quoted identifier,
// escaping any embedded double quotes.
func quotePostgresIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
