CREATE TABLE apply_operations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_id bigint NOT NULL,
  deployment varchar(255) NOT NULL,
  operation_key varchar(255) NOT NULL DEFAULT '',
  operation_kind varchar(32) NOT NULL DEFAULT 'work',
  target varchar(255) NOT NULL DEFAULT '',
  external_id varchar(255) DEFAULT NULL,
  external_operation_id varchar(255) DEFAULT NULL,
  engine_resume_context varchar(255) DEFAULT NULL,
  engine_resume_metadata jsonb DEFAULT NULL,
  state varchar(100) NOT NULL DEFAULT 'pending',
  error_message text,
  cutover_policy varchar(16) NOT NULL DEFAULT 'rolling',
  on_failure varchar(16) NOT NULL DEFAULT 'halt',
  attempt integer NOT NULL DEFAULT 0,
  lease_owner varchar(255) NOT NULL DEFAULT '',
  lease_token varchar(64) NOT NULL DEFAULT '',
  lease_acquired_at timestamp DEFAULT NULL,
  started_at timestamp DEFAULT NULL,
  completed_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_apply_operations_apply_deployment_key ON apply_operations (apply_id, deployment, operation_key);
CREATE INDEX idx_apply_operations_deployment_state ON apply_operations (deployment, state);
CREATE INDEX idx_apply_operations_state_created_id ON apply_operations (state, created_at, id);
CREATE INDEX idx_apply_operations_apply_created_id ON apply_operations (apply_id, created_at, id);
CREATE INDEX idx_apply_operations_created_id ON apply_operations (created_at, id);
