CREATE TABLE apply_target_locks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  database_name varchar(255) NOT NULL,
  database_type varchar(50) NOT NULL,
  environment varchar(50) NOT NULL,
  deployment varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_apply_target_locks_target ON apply_target_locks (database_name, database_type, environment);
CREATE UNIQUE INDEX idx_apply_target_locks_target_v2 ON apply_target_locks (database_name, database_type, environment, deployment);
