CREATE TABLE apply_control_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_id bigint NOT NULL,
  operation varchar(50) NOT NULL,
  status varchar(50) NOT NULL,
  requested_by varchar(255) NOT NULL DEFAULT '',
  error_message text,
  metadata jsonb NOT NULL,
  completed_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_apply_control_requests_apply_operation ON apply_control_requests (apply_id, operation);
CREATE INDEX idx_apply_control_requests_status ON apply_control_requests (status, created_at);
