CREATE TABLE apply_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_id bigint NOT NULL,
  task_id bigint DEFAULT NULL,
  level varchar(20) NOT NULL DEFAULT 'info',
  event_type varchar(100) NOT NULL,
  source varchar(100) NOT NULL DEFAULT 'schemabot',
  message text NOT NULL,
  old_state varchar(100) DEFAULT NULL,
  new_state varchar(100) DEFAULT NULL,
  metadata jsonb DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX idx_apply_logs_apply_created ON apply_logs (apply_id, created_at);
CREATE INDEX idx_apply_logs_task_id ON apply_logs (task_id);
CREATE INDEX idx_apply_logs_level ON apply_logs (level);
CREATE INDEX idx_apply_logs_event_type ON apply_logs (event_type);
