CREATE TABLE apply_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_id bigint NOT NULL,
  comment_state varchar(50) NOT NULL,
  github_comment_id bigint NOT NULL,
  posted_volume integer DEFAULT NULL,
  posted_phase varchar(32) DEFAULT NULL,
  pending_freeze_github_comment_id bigint DEFAULT NULL,
  observer_owner varchar(255) DEFAULT NULL,
  observer_heartbeat_at timestamp DEFAULT NULL,
  edit_count integer NOT NULL DEFAULT 0,
  last_edited_at timestamp DEFAULT NULL,
  superseded_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_apply_comments_apply_comment_state ON apply_comments (apply_id, comment_state);
CREATE INDEX idx_apply_comments_github_comment ON apply_comments (github_comment_id);
