CREATE TABLE applies (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_identifier varchar(255) NOT NULL,
  lock_id bigint NOT NULL,
  plan_id bigint NOT NULL,
  database_name varchar(255) NOT NULL,
  database_type varchar(50) NOT NULL,
  repository varchar(255) NOT NULL,
  pull_request bigint NOT NULL,
  environment varchar(50) NOT NULL,
  deployment varchar(255) NOT NULL DEFAULT '',
  caller varchar(255) NOT NULL DEFAULT '',
  installation_id bigint NOT NULL DEFAULT 0,
  external_id varchar(255) NOT NULL DEFAULT '',
  idempotency_key varchar(255) DEFAULT NULL,
  expected_operation_keys jsonb DEFAULT NULL,
  engine varchar(50) NOT NULL,
  state varchar(100) NOT NULL,
  error_message text,
  options jsonb NOT NULL,
  attempt integer NOT NULL DEFAULT 0,
  lease_owner varchar(255) NOT NULL DEFAULT '',
  lease_token varchar(64) NOT NULL DEFAULT '',
  lease_acquired_at timestamp DEFAULT NULL,
  started_at timestamp DEFAULT NULL,
  completed_at timestamp DEFAULT NULL,
  revert_skipped_at timestamp DEFAULT NULL,
  superseded_by varchar(255) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_applies_apply_identifier ON applies (apply_identifier);
CREATE UNIQUE INDEX idx_applies_idempotency_key ON applies (idempotency_key);
CREATE INDEX idx_applies_lock_id ON applies (lock_id);
CREATE INDEX idx_applies_plan_id ON applies (plan_id);
CREATE INDEX idx_applies_database_env ON applies (database_name, database_type, environment);
CREATE INDEX idx_applies_database_env_deployment ON applies (database_name, database_type, environment, deployment);
CREATE INDEX idx_applies_repo_pr ON applies (repository, pull_request);
CREATE INDEX idx_applies_created_id ON applies (created_at, id);
CREATE INDEX idx_applies_environment_created_id ON applies (environment, created_at, id);
CREATE INDEX idx_applies_state_created_id ON applies (state, created_at, id);
CREATE INDEX idx_applies_environment_state_created_id ON applies (environment, state, created_at, id);
CREATE INDEX idx_applies_completed_at_state ON applies (completed_at, state);
