CREATE TABLE checks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  repository varchar(255) NOT NULL,
  pull_request bigint NOT NULL,
  head_sha varchar(64) NOT NULL,
  environment varchar(50) NOT NULL,
  database_type varchar(50) NOT NULL,
  database_name varchar(255) NOT NULL,
  check_run_id bigint DEFAULT NULL,
  apply_id bigint DEFAULT NULL,
  has_changes boolean NOT NULL DEFAULT TRUE,
  status varchar(255) NOT NULL,
  conclusion varchar(255) DEFAULT NULL,
  blocking_reason varchar(255) DEFAULT NULL,
  error_message text,
  change_summary varchar(255) DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_checks_check_key ON checks (repository, pull_request, environment, database_type, database_name);
CREATE INDEX idx_checks_repo_env_db ON checks (repository, environment, database_type, database_name);
CREATE INDEX idx_checks_repo_pr ON checks (repository, pull_request);
CREATE INDEX idx_checks_check_run ON checks (check_run_id);
CREATE INDEX idx_checks_apply_id ON checks (apply_id);
