CREATE TABLE merge_gate_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  apply_id bigint NOT NULL,
  apply_identifier varchar(255) NOT NULL,
  environment varchar(50) NOT NULL,
  database_type varchar(50) NOT NULL,
  database_name varchar(255) NOT NULL,
  provider varchar(50) NOT NULL DEFAULT 'github',
  repository varchar(255) NOT NULL DEFAULT '',
  change_key varchar(255) NOT NULL DEFAULT '',
  requested_by varchar(255) NOT NULL DEFAULT '',
  state varchar(50) NOT NULL,
  attempts bigint NOT NULL DEFAULT 0,
  lease_owner varchar(255) DEFAULT NULL,
  lease_token varchar(64) DEFAULT NULL,
  lease_expires_at timestamp DEFAULT NULL,
  retry_after timestamp DEFAULT NULL,
  last_error text,
  completed_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_merge_gate_requests_apply ON merge_gate_requests (apply_id);
CREATE INDEX idx_merge_gate_requests_claimable ON merge_gate_requests (state, retry_after, lease_expires_at, created_at);
CREATE INDEX idx_merge_gate_requests_target ON merge_gate_requests (environment, database_type, database_name, state);
