CREATE TABLE pending_drops (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  target varchar(255) NOT NULL,
  environment varchar(50) NOT NULL,
  database_name varchar(255) NOT NULL DEFAULT '',
  original_table varchar(64) NOT NULL DEFAULT '',
  quarantined_name varchar(64) NOT NULL,
  quarantined_at timestamp NOT NULL,
  run_id varchar(255) NOT NULL DEFAULT '',
  engine varchar(50) NOT NULL,
  state varchar(20) NOT NULL,
  arrival_target varchar(255) NOT NULL DEFAULT '',
  metadata jsonb NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_pending_drops_quarantined_name ON pending_drops (target, environment, quarantined_name);
CREATE INDEX idx_pending_drops_expiry ON pending_drops (state, quarantined_at);
CREATE INDEX idx_pending_drops_origin ON pending_drops (target, environment, database_name, original_table);
