CREATE TABLE plan_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  repository varchar(255) NOT NULL,
  pull_request bigint NOT NULL,
  database_name varchar(255) NOT NULL,
  database_type varchar(50) NOT NULL,
  environment_scope varchar(255) NOT NULL DEFAULT '',
  head_sha varchar(64) NOT NULL,
  github_comment_id bigint NOT NULL,
  github_node_id varchar(255) NOT NULL,
  minimized_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX idx_plan_comments_slot ON plan_comments (repository, pull_request, database_name, database_type, minimized_at);
CREATE INDEX idx_plan_comments_github_comment ON plan_comments (github_comment_id);
