CREATE TABLE plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  plan_identifier varchar(255) NOT NULL,
  database_name varchar(255) NOT NULL,
  database_type varchar(50) NOT NULL,
  deployment varchar(255) NOT NULL DEFAULT '',
  target varchar(255) NOT NULL DEFAULT '',
  repository varchar(255) NOT NULL,
  pull_request bigint NOT NULL,
  schema_path varchar(1024) NOT NULL DEFAULT '',
  environment varchar(50) NOT NULL DEFAULT '',
  schema_files jsonb NOT NULL,
  plan_data jsonb NOT NULL,
  head_sha varchar(64) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_plans_plan_identifier ON plans (plan_identifier);
CREATE INDEX idx_plans_repo_pr ON plans (repository, pull_request);
CREATE INDEX idx_plans_database_env ON plans (database_name, database_type, environment);
