CREATE TABLE settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  setting_key varchar(255) NOT NULL,
  setting_value text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_settings_setting_key ON settings (setting_key);
