CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  task_identifier varchar(255) NOT NULL,
  apply_id bigint NOT NULL,
  apply_operation_id bigint DEFAULT NULL,
  plan_id bigint NOT NULL,
  database_name varchar(255) NOT NULL,
  database_type varchar(50) NOT NULL,
  namespace varchar(255) NOT NULL DEFAULT '',
  table_name varchar(255) DEFAULT NULL,
  shard varchar(255) NOT NULL DEFAULT '',
  ddl text,
  ddl_action varchar(50) DEFAULT NULL,
  engine varchar(50) NOT NULL,
  repository varchar(255) NOT NULL,
  pull_request bigint NOT NULL,
  environment varchar(50) NOT NULL,
  state varchar(100) NOT NULL,
  error_message text,
  options jsonb DEFAULT NULL,
  attempt integer NOT NULL DEFAULT 0,
  rows_copied bigint DEFAULT 0,
  rows_total bigint DEFAULT 0,
  progress_percent integer DEFAULT 0,
  eta_seconds integer DEFAULT NULL,
  checksum_rows_checked bigint DEFAULT 0,
  checksum_rows_total bigint DEFAULT 0,
  cutover_attempts integer NOT NULL DEFAULT 0,
  is_instant boolean DEFAULT FALSE,
  engine_migration_id varchar(255) DEFAULT NULL,
  started_at timestamp DEFAULT NULL,
  completed_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_tasks_task_identifier ON tasks (task_identifier);
CREATE INDEX idx_tasks_apply_id ON tasks (apply_id);
CREATE INDEX idx_tasks_apply_operation_id ON tasks (apply_operation_id);
CREATE INDEX idx_tasks_database ON tasks (database_name, database_type, environment, table_name);
CREATE INDEX idx_tasks_repo_pr ON tasks (repository, pull_request);
CREATE INDEX idx_tasks_state ON tasks (state);
