CREATE TABLE webhook_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  provider varchar(50) NOT NULL DEFAULT 'github',
  delivery_id varchar(64) NOT NULL,
  event varchar(100) NOT NULL,
  action varchar(100) NOT NULL DEFAULT '',
  repository varchar(255) NOT NULL DEFAULT '',
  pull_request bigint NOT NULL DEFAULT 0,
  head_sha varchar(64) NOT NULL DEFAULT '',
  tenant_id varchar(255) NOT NULL DEFAULT '',
  payload jsonb NOT NULL,
  state varchar(50) NOT NULL,
  attempts bigint NOT NULL DEFAULT 0,
  lease_owner varchar(255) DEFAULT NULL,
  lease_token varchar(64) DEFAULT NULL,
  lease_expires_at timestamp DEFAULT NULL,
  retry_after timestamp DEFAULT NULL,
  last_error text,
  received_at timestamp NOT NULL,
  started_at timestamp DEFAULT NULL,
  completed_at timestamp DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_webhook_events_provider_delivery ON webhook_events (provider, delivery_id);
CREATE INDEX idx_webhook_events_claimable ON webhook_events (state, retry_after, lease_expires_at, created_at);
CREATE INDEX idx_webhook_events_provider_repo_pr ON webhook_events (provider, repository, pull_request);
CREATE INDEX idx_webhook_events_head_sha ON webhook_events (head_sha);
CREATE INDEX idx_webhook_events_received_at ON webhook_events (received_at);
