// plans.go implements PlanStore for schema change plans.
// Plans are generated by diffing desired vs. live schema and stored for later execution.
package sqlstore

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/block/schemabot/pkg/storage"
	"github.com/block/spirit/pkg/utils"
)

// planColumns lists all columns for SELECT queries.
const planColumns = `id, plan_identifier, database_name, database_type,
	deployment, target, repository, pull_request, schema_path, environment, schema_files, plan_data, head_sha, created_at`

// planListColumns matches planColumns except schema_files, which is replaced
// by a NULL placeholder so the scan shape stays identical. schema_files holds
// the full desired-schema DDL for every table — the bulk of a plan row — and
// listings never need it, so List leaves SchemaFiles unhydrated rather than
// transferring megabytes per page.
const planListColumns = `id, plan_identifier, database_name, database_type,
	deployment, target, repository, pull_request, schema_path, environment, NULL AS schema_files, plan_data, head_sha, created_at`

// planStore implements storage.PlanStore using MySQL.
type planStore struct {
	db         *rebindDB
	identity   identityInserter
	classifier ErrorClassifier
}

// Create stores a new plan and returns its ID.
func (s *planStore) Create(ctx context.Context, plan *storage.Plan) (int64, error) {
	planDataJSON, err := json.Marshal(namespacesWithShardPlans(plan))
	if err != nil {
		return 0, fmt.Errorf("marshal plan data: %w", err)
	}

	schemaFilesJSON, err := json.Marshal(plan.SchemaFiles)
	if err != nil {
		return 0, fmt.Errorf("marshal schema files: %w", err)
	}

	id, err := s.identity.InsertID(ctx, s.db, `
		INSERT INTO plans (plan_identifier, database_name, database_type, deployment, target, repository, pull_request, schema_path, environment, schema_files, plan_data, head_sha, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	`, plan.PlanIdentifier, plan.Database, plan.DatabaseType, plan.Deployment, plan.Target, plan.Repository, plan.PullRequest, plan.SchemaPath, plan.Environment, string(schemaFilesJSON), string(planDataJSON), plan.HeadSHA, plan.CreatedAt)
	if err != nil {
		if s.classifier.IsDuplicateKey(err) {
			return 0, storage.ErrPlanIDExists
		}
		return 0, err
	}

	return id, nil
}

// Get returns a plan by plan_identifier (external identifier), or nil if not found.
func (s *planStore) Get(ctx context.Context, planIdentifier string) (*storage.Plan, error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT `+planColumns+`
		FROM plans
		WHERE plan_identifier = ?
	`, planIdentifier)

	return scanPlan(row)
}

// GetByID returns a plan by ID, or nil if not found.
func (s *planStore) GetByID(ctx context.Context, id int64) (*storage.Plan, error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT `+planColumns+`
		FROM plans
		WHERE id = ?
	`, id)

	return scanPlan(row)
}

// GetByLock returns plans for a lock.
func (s *planStore) GetByLock(ctx context.Context, lockID int64) ([]*storage.Plan, error) {
	// Plans don't have a direct lock_id, so we join through applies
	// For now, return empty - this can be implemented when needed
	return nil, nil
}

// GetByPR returns all plans for a PR, newest first.
//
// Ordering is (created_at DESC, id DESC). The id tiebreaker matters: plans.created_at
// is datetime (second precision), so two plans inserted in the same second would
// otherwise tie and MySQL could return them in either order. Callers like
// latestPlanForTarget take the first matching row as "the newest plan" and rely
// on this deterministic order to avoid picking an older SHA on ties.
func (s *planStore) GetByPR(ctx context.Context, repo string, pr int) ([]*storage.Plan, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT `+planColumns+`
		FROM plans
		WHERE repository = ? AND pull_request = ?
		ORDER BY created_at DESC, id DESC
	`, repo, pr)
	if err != nil {
		return nil, fmt.Errorf("query plans for %s#%d: %w", repo, pr, err)
	}
	defer utils.CloseAndLog(rows)

	return scanPlans(rows)
}

// List returns plans matching opts, newest first, with SchemaFiles left
// unhydrated (see planListColumns).
//
// Ordering is (created_at DESC, id DESC) for the same reason as GetByPR:
// plans.created_at is datetime (second precision), so the id tiebreaker keeps
// same-second plans in a deterministic newest-first order.
func (s *planStore) List(ctx context.Context, opts storage.ListPlansOptions) ([]*storage.Plan, error) {
	if opts.Limit <= 0 {
		return nil, fmt.Errorf("list plans for database %q environment %q: limit must be positive, got %d", opts.Database, opts.Environment, opts.Limit)
	}

	var where []string
	var args []any
	if opts.Database != "" {
		where = append(where, "database_name = ?")
		args = append(args, opts.Database)
	}
	if opts.Environment != "" {
		where = append(where, "environment = ?")
		args = append(args, opts.Environment)
	}
	if opts.Repository != "" {
		where = append(where, "repository = ?")
		args = append(args, opts.Repository)
	}
	if opts.PullRequest > 0 {
		where = append(where, "pull_request = ?")
		args = append(args, opts.PullRequest)
	}
	if !opts.Since.IsZero() {
		where = append(where, "created_at >= ?")
		args = append(args, opts.Since)
	}

	query := "SELECT " + planListColumns + " FROM plans"
	if len(where) > 0 {
		query += " WHERE " + strings.Join(where, " AND ")
	}
	query += " ORDER BY created_at DESC, id DESC LIMIT ?"
	args = append(args, opts.Limit)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("list plans for database %q environment %q: %w", opts.Database, opts.Environment, err)
	}
	defer utils.CloseAndLog(rows)

	return scanPlans(rows)
}

// Delete removes a plan by ID.
func (s *planStore) Delete(ctx context.Context, id int64) error {
	result, err := s.db.ExecContext(ctx, `DELETE FROM plans WHERE id = ?`, id)
	if err != nil {
		return err
	}
	return checkRowsAffected(result, storage.ErrPlanNotFound)
}

// DeleteByPR removes all plans for a PR.
func (s *planStore) DeleteByPR(ctx context.Context, repo string, pr int) error {
	_, err := s.db.ExecContext(ctx, `DELETE FROM plans WHERE repository = ? AND pull_request = ?`, repo, pr)
	return err
}

// scanPlan scans a single plan row, returning nil if not found.
func scanPlan(row *sql.Row) (*storage.Plan, error) {
	plan, err := scanPlanInto(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return plan, err
}

// scanPlans scans multiple plan rows.
func scanPlans(rows *sql.Rows) ([]*storage.Plan, error) {
	var plans []*storage.Plan
	for rows.Next() {
		plan, err := scanPlanInto(rows)
		if err != nil {
			return nil, err
		}
		plans = append(plans, plan)
	}
	return plans, rows.Err()
}

// scanPlanInto scans plan data from any scanner (Row or Rows).
func scanPlanInto(s scanner) (*storage.Plan, error) {
	var plan storage.Plan
	var schemaFilesJSON []byte
	var planDataJSON []byte

	err := s.Scan(
		&plan.ID,
		&plan.PlanIdentifier,
		&plan.Database,
		&plan.DatabaseType,
		&plan.Deployment,
		&plan.Target,
		&plan.Repository,
		&plan.PullRequest,
		&plan.SchemaPath,
		&plan.Environment,
		&schemaFilesJSON,
		&planDataJSON,
		&plan.HeadSHA,
		&plan.CreatedAt,
	)
	if err != nil {
		return nil, err
	}

	// Parse schema_files JSON
	if len(schemaFilesJSON) > 0 {
		if err := json.Unmarshal(schemaFilesJSON, &plan.SchemaFiles); err != nil {
			return nil, fmt.Errorf("unmarshal schema files: %w", err)
		}
	}

	// Parse plan_data JSON (namespace-keyed format)
	if len(planDataJSON) > 0 {
		if err := json.Unmarshal(planDataJSON, &plan.Namespaces); err != nil {
			return nil, fmt.Errorf("unmarshal plan data: %w", err)
		}
		plan.Shards = shardPlansFromNamespaces(plan.Namespaces)
	}

	return &plan, nil
}

func namespacesWithShardPlans(plan *storage.Plan) map[string]*storage.NamespacePlanData {
	if len(plan.Namespaces) == 0 && len(plan.Shards) == 0 {
		return plan.Namespaces
	}
	namespaces := make(map[string]*storage.NamespacePlanData, len(plan.Namespaces))
	for namespace, nsData := range plan.Namespaces {
		if nsData == nil {
			namespaces[namespace] = nil
			continue
		}
		// Plan.Shards is the authoritative flattened write path. Existing
		// namespace-embedded shards are preserved only when the caller did not
		// supply flattened shards, such as when re-storing an older decoded shape.
		shards := append([]storage.ShardPlan(nil), nsData.Shards...)
		if len(plan.Shards) > 0 {
			shards = nil
		}
		namespaces[namespace] = &storage.NamespacePlanData{
			Tables:                append([]storage.TableChange(nil), nsData.Tables...),
			Shards:                shards,
			OriginalFiles:         nsData.OriginalFiles,
			OriginalFilesCaptured: nsData.OriginalFilesCaptured,
			Artifacts:             nsData.Artifacts,
		}
	}
	for _, shard := range sortedShardPlans(plan.Shards) {
		namespace := planShardNamespace(shard.Namespace)
		shard.Namespace = namespace
		if namespaces[namespace] == nil {
			namespaces[namespace] = &storage.NamespacePlanData{}
		}
		namespaces[namespace].Shards = append(namespaces[namespace].Shards, shard)
	}
	return namespaces
}

func shardPlansFromNamespaces(namespaces map[string]*storage.NamespacePlanData) []storage.ShardPlan {
	var shards []storage.ShardPlan
	for namespace, nsData := range namespaces {
		if nsData == nil {
			continue
		}
		for _, shard := range nsData.Shards {
			if shard.Namespace == "" {
				shard.Namespace = planShardNamespace(namespace)
			}
			shards = append(shards, shard)
		}
	}
	return sortedShardPlans(shards)
}

func sortedShardPlans(shards []storage.ShardPlan) []storage.ShardPlan {
	out := append([]storage.ShardPlan(nil), shards...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].Namespace != out[j].Namespace {
			return out[i].Namespace < out[j].Namespace
		}
		return out[i].Shard < out[j].Shard
	})
	return out
}

func planShardNamespace(namespace string) string {
	if namespace == "" {
		return "default"
	}
	return namespace
}
