//go:build integration

package sqlstore

import (
	"database/sql"
	"fmt"
	"testing"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/block/schemabot/pkg/namedlock"
	"github.com/block/schemabot/pkg/postgresconn"
	"github.com/block/schemabot/pkg/schema"
	"github.com/block/schemabot/pkg/storage"
	"github.com/block/schemabot/pkg/storage/storagetest"
	"github.com/block/schemabot/pkg/testutil"
)

type postgresHarness struct {
	db  *sql.DB
	dsn string
}

func (h postgresHarness) NewStorage(t *testing.T) storage.Storage {
	t.Helper()
	clearPostgresTables(t, h.db)
	dialect := PostgresDialect{}
	return NewWithDependencies(Dependencies{
		DB:         h.db,
		Binder:     dialect,
		Dialect:    dialect,
		Identity:   dialect,
		Locker:     namedlock.Postgres{},
		Classifier: NewPostgresErrorClassifier(),
	})
}

func (h postgresHarness) NewUnreachableStorage(t *testing.T) storage.Storage {
	t.Helper()
	db, err := sql.Open("pgx", h.dsn)
	require.NoError(t, err)
	require.NoError(t, db.Close())
	dialect := PostgresDialect{}
	return NewWithDependencies(Dependencies{
		DB:         db,
		Binder:     dialect,
		Dialect:    dialect,
		Identity:   dialect,
		Locker:     namedlock.Postgres{},
		Classifier: NewPostgresErrorClassifier(),
	})
}

func TestPostgresStorageParity(t *testing.T) {
	dsn, fixtureDB := testutil.StartPostgres(t, "sqlstore_parity")
	db, err := postgresconn.Open(dsn)
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })
	require.NoError(t, db.PingContext(t.Context()))
	applyPostgresTestSchema(t, fixtureDB)

	h := postgresHarness{db: db, dsn: dsn}
	t.Run("Settings", func(t *testing.T) { storagetest.TestSettings(t, h) })
	t.Run("ApplyLogs", func(t *testing.T) { testPostgresApplyLogsParity(t, h) })
}

// testPostgresApplyLogsParity exercises the ApplyLogs family without creating
// its parent through ApplyStore. ApplyStore creation still contains a MySQL
// index hint, while apply_logs itself is independent of that SQL family.
func testPostgresApplyLogsParity(t *testing.T, h postgresHarness) {
	store := h.NewStorage(t)
	ctx := t.Context()
	for i := 1; i <= 4; i++ {
		require.NoError(t, store.ApplyLogs().Append(ctx, &storage.ApplyLog{
			ApplyID:   42,
			Level:     storage.LogLevelInfo,
			EventType: storage.LogEventInfo,
			Message:   fmt.Sprintf("entry %d", i),
			Metadata:  fmt.Appendf(nil, `{"ordinal":%d}`, i),
		}))
	}

	all, err := store.ApplyLogs().GetByApply(ctx, 42)
	require.NoError(t, err)
	require.Len(t, all, 4)
	for i, entry := range all {
		assert.Equal(t, fmt.Sprintf("entry %d", i+1), entry.Message)
		assert.JSONEq(t, fmt.Sprintf(`{"ordinal":%d}`, i+1), string(entry.Metadata))
	}
	recent, err := store.ApplyLogs().GetRecentByApply(ctx, 42, 2)
	require.NoError(t, err)
	require.Len(t, recent, 2)
	assert.Equal(t, "entry 3", recent[0].Message)
	assert.Equal(t, "entry 4", recent[1].Message)
	listed, err := store.ApplyLogs().List(ctx, storage.ApplyLogFilter{ApplyID: 42, Limit: 2})
	require.NoError(t, err)
	require.Len(t, listed, 2)
	assert.Equal(t, "entry 3", listed[0].Message)
	assert.Equal(t, "entry 4", listed[1].Message)
}

func TestPGXStdlibValueContracts(t *testing.T) {
	_, db := testutil.StartPostgres(t, "sqlstore_values")
	_, err := db.ExecContext(t.Context(), `CREATE TABLE value_contracts (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		flag boolean NOT NULL,
		payload jsonb NOT NULL,
		observed_at timestamptz NOT NULL,
		label text NOT NULL
	)`)
	require.NoError(t, err)

	wantTime := time.Date(2026, time.August, 11, 12, 34, 56, 123456000, time.FixedZone("test", 2*60*60))
	_, err = db.ExecContext(t.Context(),
		`INSERT INTO value_contracts (flag, payload, observed_at, label) VALUES ($1, $2, $3, $4)`,
		true, []byte(`{"enabled":true}`), wantTime, "same")
	require.NoError(t, err)

	var gotBool bool
	var gotJSON []byte
	var gotTime time.Time
	require.NoError(t, db.QueryRowContext(t.Context(),
		`SELECT flag, payload, observed_at FROM value_contracts WHERE id = 1`,
	).Scan(&gotBool, &gotJSON, &gotTime))
	assert.True(t, gotBool)
	assert.JSONEq(t, `{"enabled":true}`, string(gotJSON))
	assert.Equal(t, wantTime.UTC(), gotTime.UTC())
	assert.Equal(t, wantTime.Nanosecond(), gotTime.Nanosecond(), "timestamptz retains microsecond precision")

	result, err := db.ExecContext(t.Context(), `UPDATE value_contracts SET label = $1 WHERE id = $2`, "same", 1)
	require.NoError(t, err)
	affected, err := result.RowsAffected()
	require.NoError(t, err)
	assert.Equal(t, int64(1), affected, "PostgreSQL reports matched rows even when values are unchanged")
}

func applyPostgresTestSchema(t *testing.T, db *sql.DB) {
	t.Helper()
	entries, err := schema.PostgresFS.ReadDir("postgres")
	require.NoError(t, err)
	for _, entry := range entries {
		content, readErr := schema.PostgresFS.ReadFile("postgres/" + entry.Name())
		require.NoError(t, readErr)
		_, execErr := db.ExecContext(t.Context(), string(content))
		require.NoError(t, execErr, "execute %s", entry.Name())
	}
}

func clearPostgresTables(t *testing.T, db *sql.DB) {
	t.Helper()
	rows, err := db.QueryContext(t.Context(), `SELECT tablename FROM pg_tables WHERE schemaname = 'public'`)
	require.NoError(t, err)
	var tables []string
	for rows.Next() {
		var table string
		require.NoError(t, rows.Scan(&table))
		tables = append(tables, table)
	}
	require.NoError(t, rows.Close())
	require.NoError(t, rows.Err())
	for _, table := range tables {
		_, err := db.ExecContext(t.Context(), fmt.Sprintf(`TRUNCATE TABLE %q RESTART IDENTITY CASCADE`, table))
		require.NoError(t, err)
	}
}
