#!/usr/bin/env python3
"""Insert or refresh a Table of Contents in Markdown files under docs/.

Run via `make docs-toc` (see Makefile). `make check-docs-toc` runs the same
generation in check mode (`--check`): nothing is written, and the exit code
is non-zero if any committed TOC differs from what generation would produce.
CI runs the check so a stale TOC fails the PR instead of drifting.

The TOC lists H2 and H3 headings (skipping headings inside fenced code
blocks), uses GitHub-style slug anchors, and is placed immediately after the
leading H1. The block is wrapped in BEGIN/END markers so a re-run replaces
it in place instead of appending a duplicate. Run this after adding or
renaming headings in any doc.

A TOC is opt-in per file: the sweep over docs/**/*.md only refreshes files
that already carry the markers. To give a new doc a TOC, name it explicitly
(`python3 scripts/gen-doc-toc.py docs/new-doc.md`), which inserts the marker
block; a doc without markers stays TOC-free through both the sweep and the
check.

The opt-in set is pinned by docs/.toc-manifest, regenerated on every write
run. The check fails when a file listed there no longer carries the markers,
so a TOC can't be dropped silently: removing one on purpose means deleting
the marker block and running `make docs-toc`, which records the removal as
a reviewable manifest change.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN TOC (auto-generated by `make docs-toc`) -->"
END = "<!-- END TOC (auto-generated by `make docs-toc`) -->"

MANIFEST = Path("docs/.toc-manifest")
MANIFEST_HEADER = [
    "# Files that carry an auto-generated Table of Contents.",
    "# Regenerated by `make docs-toc`. The check fails when a file listed",
    "# here loses its TOC markers, so a TOC can't be dropped silently: to",
    "# remove one on purpose, delete the marker block and run `make docs-toc`",
    "# so the removal shows up here as a reviewable change.",
]

FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
CLOSING_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})\s*$")


def slugify(text: str) -> str:
    # GitHub's slugger: lowercase, drop punctuation except `-` and `_`, and
    # replace each whitespace character with its own `-` (so punctuation
    # stripped between two spaces yields `--`, exactly as GitHub renders it).
    # Underscores are preserved because GitHub treats them as word characters
    # in heading anchors.
    text = text.strip().lower()
    text = re.sub(r"[^\w\s\-]", "", text, flags=re.UNICODE)
    text = re.sub(r"\s", "-", text)
    return text


def content_lines(lines: list[str]) -> list[tuple[int, str]]:
    """Return (index, line) pairs for lines outside fenced code blocks.

    Tracks the opening fence's character and length so nested fences
    (a shorter ``` inside a ```` block, or a ``` inside a ~~~ block) don't
    desynchronize the scan: a fence only closes on a line of at least as
    many of the same character with nothing else on it.
    """
    out: list[tuple[int, str]] = []
    open_fence: str | None = None
    for i, line in enumerate(lines):
        if open_fence is None:
            m = FENCE.match(line)
            if m:
                open_fence = m.group(1)
                continue
            out.append((i, line))
        else:
            m = CLOSING_FENCE.match(line)
            if m and m.group(1)[0] == open_fence[0] and len(m.group(1)) >= len(open_fence):
                open_fence = None
    return out


def parse_headings(lines: list[str]) -> list[tuple[int, str]]:
    """Return (level, text) for every H1-H6 outside fenced code blocks.

    All levels are collected so duplicate-anchor numbering matches GitHub,
    which counts every heading level; build_toc lists only H2/H3.
    """
    headings: list[tuple[int, str]] = []
    for _, line in content_lines(lines):
        m = re.match(r"^(#{1,6})\s+(.+?)\s*$", line)
        if m:
            headings.append((len(m.group(1)), m.group(2)))
    return headings


def build_toc(headings: list[tuple[int, str]]) -> str:
    if not any(level in (2, 3) for level, _ in headings):
        return ""
    lines = ["## Table of Contents", ""]
    slug_counts: dict[str, int] = {}
    for level, text in headings:
        slug = slugify(text)
        count = slug_counts.get(slug, 0)
        slug_counts[slug] = count + 1
        if level not in (2, 3):
            continue
        anchor = slug if count == 0 else f"{slug}-{count}"
        indent = "  " * (level - 2)
        lines.append(f"{indent}- [{text}](#{anchor})")
    lines.append("")
    return "\n".join(lines)


def regenerate(original: str) -> str | None:
    """Return the file content with a fresh TOC, or None for a heading-less file."""
    # Strip any existing auto-generated TOC block (matches the current and
    # any prior marker text so re-runs after a marker change still work).
    text = re.sub(
        r"<!-- BEGIN TOC[^>]*-->.*?<!-- END TOC[^>]*-->\n*",
        "",
        original,
        flags=re.DOTALL,
    )
    lines = text.splitlines()

    headings = parse_headings(lines)
    toc_body = build_toc(headings)
    if not toc_body:
        return None

    # Insert after the leading H1 (and its trailing blank line, if any),
    # skipping H1-looking lines inside fenced code blocks.
    insert_at = 0
    for i, line in content_lines(lines):
        if line.startswith("# "):
            insert_at = i + 1
            if insert_at < len(lines) and lines[insert_at].strip() == "":
                insert_at += 1
            break

    block = [BEGIN, "", toc_body.rstrip(), "", END, ""]
    new_lines = lines[:insert_at] + block + lines[insert_at:]
    new_text = "\n".join(new_lines)
    if not new_text.endswith("\n"):
        new_text += "\n"
    return new_text


def has_toc_markers(text: str) -> bool:
    return re.search(r"<!-- BEGIN TOC[^>]*-->", text) is not None


def marked_files() -> list[Path]:
    """The docs files currently carrying TOC markers, in sorted order."""
    return sorted(
        p for p in Path("docs").glob("**/*.md") if has_toc_markers(p.read_text())
    )


def write_manifest(files: list[Path]) -> bool:
    """Rewrite the manifest to the given file set. Returns True on change."""
    text = "\n".join([*MANIFEST_HEADER, *[str(p) for p in files], ""])
    if MANIFEST.exists() and MANIFEST.read_text() == text:
        return False
    MANIFEST.write_text(text)
    return True


def read_manifest() -> list[Path] | None:
    if not MANIFEST.exists():
        return None
    return [
        Path(line)
        for line in MANIFEST.read_text().splitlines()
        if line and not line.startswith("#")
    ]


def manifest_problems(actual: list[Path]) -> list[str]:
    """Compare the manifest against the marker-carrying files on disk."""
    manifest = read_manifest()
    if manifest is None:
        return [f"{MANIFEST} is missing; run `make docs-toc` to create it"]
    problems = []
    for p in manifest:
        if p not in actual:
            problems.append(
                f"{p} is listed in {MANIFEST} but no longer carries TOC markers; "
                "restore its TOC, or run `make docs-toc` to record the removal"
            )
    for p in actual:
        if p not in manifest:
            problems.append(
                f"{p} carries TOC markers but is not listed in {MANIFEST}; "
                "run `make docs-toc` and commit the result"
            )
    return problems


def process(path: Path, insert: bool, check: bool) -> str:
    """Refresh one file's TOC. Returns a status string."""
    original = path.read_text()
    if not insert and not has_toc_markers(original):
        return "skipped"
    new_text = regenerate(original)
    if new_text is None:
        # The file opted in (markers present, or named explicitly) but has no
        # H2/H3 headings to list — a broken TOC, not a current one.
        return "no-headings"
    if new_text == original:
        return "current"
    if check:
        return "stale"
    path.write_text(new_text)
    return "updated"


def main(argv: list[str]) -> int:
    args = argv[1:]
    check = "--check" in args
    args = [a for a in args if a != "--check"]
    explicit = [Path(p) for p in args]
    paths = explicit or sorted(Path("docs").glob("**/*.md"))

    stale: list[Path] = []
    broken: list[Path] = []
    changed = 0
    examined = 0
    for p in paths:
        status = process(p, insert=bool(explicit), check=check)
        if status == "skipped":
            continue
        examined += 1
        if status == "stale":
            stale.append(p)
        elif status == "no-headings":
            broken.append(p)
        elif status == "updated":
            print(f"updated {p}")
            changed += 1

    failed = False
    for p in broken:
        print(f"broken TOC: {p} has TOC markers but no H2/H3 headings to list")
        failed = True

    if not explicit and examined == 0:
        # A sweep that finds nothing to check would pass vacuously — fail
        # loudly instead so a moved docs/ tree can't silently disable the gate.
        print("no files with TOC markers found under docs/")
        return 1

    if check:
        # A file can't opt out of the check by dropping its marker block:
        # the manifest pins the opt-in set, and only a write run may move it.
        for problem in manifest_problems(marked_files()):
            print(problem)
            failed = True
        if stale:
            for p in stale:
                print(f"stale TOC: {p}")
            print("Run `make docs-toc` and commit the result.")
            failed = True
        if failed:
            return 1
        print(f"all TOCs are current ({examined} file(s) checked)")
        return 0

    if write_manifest(marked_files()):
        print(f"updated {MANIFEST}")

    if failed:
        return 1
    print(f"{changed} of {examined} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
