#!/usr/bin/env python3
"""Prepare GitHub-rendered comment bodies for the illustrative README recording.
Uses the existing mockup renderer and real templates, with one consistent SQL fixture.
Requires authenticated gh; render-pr-demo.cjs uses the committed output offline.
"""
from pathlib import Path
import json,re,runpy
root=Path(__file__).resolve().parent.parent
m=runpy.run_path(str(root/'scripts/render-pr-mockups.py'))
sections=m['load_sections']();cache={}
ddl='ALTER TABLE `users` ADD INDEX `idx_email_created`(`email`, `created_at`);'
def common(s):
 return m['prepare'](s).replace('2026-01-01 00:00:00 UTC','2026-09-01 10:00:00 UTC').replace('2026-03-14 10:30:00 UTC','2026-09-01 10:00:00 UTC')
comments={}
for name,anchor in [('plan','mysql-plan'),('apply','schema-change-apply-automatic')]:
 s=common(sections[anchor]);s=re.sub(r'```sql\n.*?```','```sql\n'+ddl+'\n```',s,count=1,flags=re.S)
 s=re.sub(r'💡 \*\*Lint Warnings\*\*.*?(?=📋)', '',s,flags=re.S)
 s=s.replace('**2** tables to create, **1** table to alter','**1** table to alter')
 comments[name]=m['render_markdown'](s,cache)
s=common(sections['single-table-running'])
s=re.sub(r'🟦.*?48\.61%', 'DEMOVALUEBARTOKEN DEMOVALUEPERCENTTOKEN%',s)
s=s.replace('3,500,000','DEMOVALUEROWSTOKEN').replace('5m 30s','DEMOVALUEETATOKEN')
comments['running']=m['render_markdown'](s,cache)
comments['complete']=m['render_markdown'](common(sections['single-table-completed']),cache)
s=common(sections['summary-completed']);a=s.index('<details>');s=s[:a]+f'<details><summary>Apply details (1 table)</summary>\n\n_Apply ID: `apply-a1b2c3d4e5f6`_\n\n**`users`**\n```sql\n{ddl}\n```\n\n</details>'
comments['summary']=m['render_markdown'](s,cache)
# Use GitHub's SQL highlighter for the opening file diff, too.
schema="""CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  KEY `idx_email_created` (`email`, `created_at`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;"""
highlighted=m['render_markdown']('```sql\n'+schema+'\n```',cache)
comments['diffLines']=re.search(r'<pre\b[^>]*>(.*?)</pre>',highlighted,re.S).group(1).splitlines()
assert len(comments['diffLines'])==7
(root/'assets/src/pr-workflow-comments.js').write_text('// Generated by scripts/prepare-pr-demo.py from TEMPLATES.md\nwindow.COMMENTS = '+json.dumps(comments,ensure_ascii=False)+';\n')
(root/'assets/src/pr-workflow-comments.css').write_text('/* Shared with the static PR mockups; generated by prepare-pr-demo.py */\n'+m['CSS'])
print('Prepared five GitHub-rendered comment bodies')
