CREATE TABLE `merge_gate_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `apply_id` bigint unsigned NOT NULL,
  `kind` varchar(20) NOT NULL,
  `apply_identifier` varchar(255) NOT NULL,
  `environment` varchar(50) NOT NULL,
  `database_type` varchar(50) NOT NULL,
  `database_name` varchar(255) NOT NULL,
  `provider` varchar(50) NOT NULL DEFAULT 'github',
  `repository` varchar(255) NOT NULL DEFAULT '',
  `change_key` varchar(255) NOT NULL DEFAULT '',
  `requested_by` varchar(255) NOT NULL DEFAULT '',
  `state` varchar(50) NOT NULL,
  `attempts` int unsigned NOT NULL DEFAULT '0',
  `lease_owner` varchar(255) DEFAULT NULL,
  `lease_token` varchar(64) DEFAULT NULL,
  `lease_expires_at` datetime(6) DEFAULT NULL,
  `retry_after` datetime DEFAULT NULL,
  `last_error` text,
  `holds_recorded_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_merge_gate_apply` (`apply_id`,`kind`),
  KEY `idx_merge_gate_claimable` (`state`,`retry_after`,`lease_expires_at`,`created_at`),
  KEY `idx_merge_gate_target` (`environment`,`database_type`,`database_name`,`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
