CREATE TABLE `webhook_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `delivery_id` varchar(64) NOT NULL,
  `event` varchar(100) NOT NULL,
  `action` varchar(100) NOT NULL DEFAULT '',
  `repository` varchar(255) NOT NULL DEFAULT '',
  `pull_request` int unsigned NOT NULL DEFAULT '0',
  `head_sha` varchar(64) NOT NULL DEFAULT '',
  `installation_id` bigint unsigned NOT NULL DEFAULT '0',
  `payload` json NOT NULL,
  `state` varchar(50) NOT NULL,
  `attempts` int unsigned NOT NULL DEFAULT '0',
  `lease_owner` varchar(255) DEFAULT NULL,
  `lease_token` varchar(64) DEFAULT NULL,
  `lease_expires_at` datetime DEFAULT NULL,
  `retry_after` datetime DEFAULT NULL,
  `last_error` text,
  `received_at` datetime NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_delivery_id` (`delivery_id`),
  KEY `idx_claimable` (`state`,`retry_after`,`lease_expires_at`,`created_at`),
  KEY `idx_repo_pr` (`repository`,`pull_request`),
  KEY `idx_head_sha` (`head_sha`),
  KEY `idx_received_at` (`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
